#!/bin/bash


dbus-update-activation-environment --all
#xrandr --dpi 100
xsetroot -cursor_name left_ptr

xinput --set-prop bcm5974 "libinput Natural Scrolling Enabled" 1

#export $_JAVA_AWT_WM_NONREPARENTING=1

#disable slow starting of gnome apps
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

$HOME/.config/bspwm/background

#bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc rule -a "firefox" desktop="^1"
bspc rule -a "discord" desktop="^3"

bspc config border_width         1
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

# Polybar
$HOME/.config/polybar/launch

xsetroot -cursor_name left_ptr

sxhkd & # Keybinds
btops &
wal -i $HOME/.config/wal/backgrounds &

xset -b

nm-applet & # Networkmanager
dunst &
firefox &
discord &
picom &
lxqt-policykit-agent &


$HOME/.config/bspwm/resize &

# Remap caps lock to escape
setxkbmap -option caps:swapescape
