#!/bin/bash

while true; do
    bspc subscribe monitor_geometry | head -1 # wait for resize event
    notify-send "Resize detected, updating!"
    $HOME/.config/polybar/launch &
    xinput --map-to-output $(xinput list --id-only "Wacom HID 48DE Finger") eDP-1 &
done
