#!/usr/bin/env sh

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done


if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar top -c ~/.config/polybar/config-top.ini &
    MONITOR=$m polybar bottom -c ~/.config/polybar/config-bottom.ini &
  done
else
  polybar top -c ~/.config/polybar/config-top.ini &
  polybar bottom -c ~/.config/polybar/config-bottom.ini &
fi

